---
name: lint-jsonnet
on: [pull_request]
  # pull_request:
  #   paths: "production/**"

jobs:
  lint-jsonnet:
    name: Lint Jsonnet files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: setup jsonnet
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt@v0.20.0
          go install github.com/google/go-jsonnet/cmd/jsonnet-lint@v0.20.0
          go install github.com/monitoring-mixins/mixtool/cmd/mixtool@a9e78b0942a4186162bf170efde7b4b3167d31a4
          go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@v0.5.1
      - name: run linting
        run: make BUILD_IN_CONTAINER=false lint-jsonnet

